sudo: false
language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
node_js:
  - '4.1'
before_install:
  - export CHROME_BIN=chromium-browser
  - npm i -g npm@^2.0.0
  - npm install -g gulp
  - npm install
before_script:
  - npm prune
after_success:
  - npm run semantic-release
